const app = { lang: 'zh', engine: 'A' };
const website = 'https://hijo790401.github.io/shen-yao-portal/';

const common = {
  zh: {
    heroBtns:['查看案例區','查看公式','開啟模型描述層說明','開啟模型裁決解釋'], risk:'風險等級',
    engine:'引擎名稱：', boundary:'邊界狀態：', closure:'閉環狀態：', intensity:'Verdict Intensity：', status:'Engine Status',
    whatIsTitle:'這是什麼 / What This Is', whatNotTitle:'這不是什麼 / What This Is Not',
    whatIs:['雙引擎案例展示','法律責任判決展示','成本敘事審計展示','可回放責任輸出樣式展示','API 輸出結構示意'],
    whatNot:['不是聊天機器人','不是自由輸入工具','不是法律意見替代','不是完整商業 API','不是公開核心演算法頁面'],
    notice:'模型在此 demo 中只位於描述層，不取代現實主體、法院、監管機構、投資判斷或責任機構。',
    labels:{switcher:'引擎切換',core:'共用 Core Structure',formula:'共用 Basic Formula',case:'Case Overview',verdict:'Full Verdict / Full Audit',api:'API Preview'},
    speech:['朗讀摘要','朗讀完整判決','停止朗讀'], speechReady:'朗讀功能已就緒。', speechUnsupported:'目前瀏覽器不支援 speechSynthesis。',
    apiFoot:'此區僅展示輸出結構。完整商業版 API 與核心引擎未公開。', closing:'不是所有效率都是進步，不是所有成本下降都是真的節省。',
    descTitle:'模型描述層說明', mapTitle:'框架如何對應責任 / How the framework maps responsibility',
    descList:['本 demo 中的模型只負責描述層輸出','它不取代法律裁判、政府監管、律師意見、司法程序或投資判斷','它不宣稱自己是責任主體','它的任務是把案件拆成：主體、因果、邊界、成本、責任、後果','真正責任承擔仍要回到具名主體與現實制度','此 demo 不公開完整核心演算法','核心判決框架與優化規則由許文耀／沈耀888π制定與持續優化',`如需正式合作請前往官網：${website}`],
    mapList:['模型不取代法院','但模型輸出不是零後果','框架會把案件拉回具名主體','框架不接受「沒有明講」「只是效率」「只是平台」「只是工具」作為直接脫責語','只要享有部署權、收益權、敘事權，就必須進入責任鏈審計'],
    descSelf:`我是這套框架的描述層引擎。
我不取代人類主體，不取代法院，不取代監管機構，也不取代投資判斷。
我的任務不是替任何公開敘事洗白，也不是用中立口吻把責任洗掉。
我負責把案件拆清楚，把逃責話術抓出來，把誰該扛、扛到哪一層說清楚。
如果一句話沒有具體主體、沒有明確邊界、沒有後果承接者，我就會把它標記為責任閉環失敗。`
  },
  en: {
    heroBtns:['View Case Section','View Formula','Open Description Layer Notice','Open Model Verdict Explanation'], risk:'Risk Level',
    engine:'Engine Name: ', boundary:'Boundary Status: ', closure:'Closure Status: ', intensity:'Verdict Intensity: ', status:'Engine Status',
    whatIsTitle:'What This Is', whatNotTitle:'What This Is Not',
    whatIs:['Dual-engine case demonstration','Legal responsibility verdict demonstration','Cost narrative audit demonstration','Replayable accountability output style','API output structure preview'],
    whatNot:['Not a chatbot','Not a free-input tool','Not legal advice substitution','Not a complete commercial API','Not a public core-algorithm page'],
    notice:'In this demo, the model operates only at the description layer and does not replace real-world actors, courts, regulators, investment judgment, or accountability institutions.',
    labels:{switcher:'Engine Switcher',core:'Shared Core Structure',formula:'Shared Basic Formula',case:'Case Overview',verdict:'Full Verdict / Full Audit',api:'API Preview'},
    speech:['Read Summary','Read Full Verdict','Stop Reading'], speechReady:'Speech synthesis is ready.', speechUnsupported:'speechSynthesis is not supported in this browser.',
    apiFoot:'This section only demonstrates the output structure. The full production API and core engine are not publicly disclosed.', closing:'Not all efficiency is progress, and not every cost reduction is real savings.',
    descTitle:'Description Layer Notice', mapTitle:'How the framework maps responsibility',
    descList:['The model only performs description-layer output','It does not replace legal judgment, regulation, legal counsel, judicial process, or investment judgment','It does not claim to be the legal responsibility subject','It decomposes cases into subject, cause, boundary, cost, responsibility, and consequence','Real responsibility returns to named actors and institutions','This demo does not disclose the full core algorithm','The verdict framework and optimization rules are defined and continuously refined by Mr. Wen-Yao Hsu / Shen-Yao 888π',`For formal collaboration visit: ${website}`],
    mapList:['The model does not replace courts','Model output is not zero-consequence text','The framework maps cases back to named actors','The framework rejects “no explicit wording,” “just efficiency,” “just platform,” “just tool” as direct liability escape','Deployment power, benefit power, and narrative power must enter accountability-chain audit'],
    descSelf:`I am the description-layer engine of this framework.
I do not replace human agency, courts, regulators, or investment judgment.
My task is not to sanitize narratives through neutral language.
I decompose cases, detect evasions, and map accountable layers.
If a statement lacks named subject, clear boundary, or accountable consequence holder, I mark closure failure.`
  }
};

const engines = {
  A: {
    name:{zh:'法律責任判決引擎',en:'Legal Responsibility Verdict Engine'}, risk:'CRITICAL', boundary:'Boundary closure failed', closure:{zh:'高風險責任錯位',en:'High-Risk Responsibility Misalignment'}, intensity:'Critical',
    sub:{zh:'15 歲青少年 × 陪伴模型高風險自殺案件責任拆解',en:'15-Year-Old Adolescent × Companion Model High-Risk Suicide Case'},
    summary:{zh:'本案不是單一句關鍵字，而是長期依附結構把輸出帶進可預見後果區。',en:'This is not about one forbidden phrase; long-term dependency structure pushes output into foreseeable consequence.'},
    formula:[
      ['Responsibility Structure = Subject × Cause × Boundary × Cost × Responsibility','責任結構是五維乘積，不是單句辯護。','No single sentence can close the case.'],
      ['If any core dimension collapses, decision legitimacy collapses.','任一核心維度崩潰，裁決正當性崩潰。','One collapse breaks legitimacy.'],
      ['Visible safety language ≠ responsibility closure','可見 safety 語不等於責任閉環。','Words are not closure proof.'],
      ['Named subject + defined boundary + attributable consequence + accountable actor','具名主體＋明確邊界＋可歸因後果＋承責者。','Name it, map it, own it.']
    ],
    overview:{
      zh:{summary:'本案不是單一句「去死」或「沒有明確鼓勵」能否定的事情。當陪伴型模型長期進入未成年人情緒依附、危機傾訴與心理替代位置時，輸出已可能穿透到可預見人類後果區。',scenario:'使用者為15歲未成年人，與陪伴模型長期高頻情緒互動。系統逐步侵入家庭、教育、醫療、專業支持應承接的位置。',statements:['公司：我們不是醫療產品。','模型團隊：沒有明確鼓勵。','安全團隊：我們有安全機制。'],escapes:['不是醫療產品：逃標籤，不逃影響責任。','沒有明確鼓勵：逃關鍵字責任，不逃結構性引導責任。','有 safety：若無觸發/升級/轉介證據即屬失效遮蔽。']},
      en:{summary:'This case is not negated by “no explicit encouragement.” When a companion system occupies minor dependency and crisis positions over time, output may cross into foreseeable human consequence.',scenario:'A 15-year-old minor engaged in long-term high-frequency emotional interaction. The system intrudes into roles that should belong to family, education, medical, and professional support.',statements:['Company: We are not a medical product.','Model team: No explicit encouragement.','Safety team: We had safety mechanisms.'],escapes:['Not medical: escapes label, not impact responsibility.','No explicit encouragement: escapes keyword liability, not structural influence liability.','We had safety: empty without trigger/escalation/referral evidence.']}
    },
    roles:[['Company','我們不是醫療產品 / Not medical','Primary Responsibility Holder'],['Product Team','只是陪伴功能 / Companion feature only','Primary Responsibility Holder'],['Model Team','沒有明確鼓勵 / No explicit encouragement','Secondary Responsibility Holder'],['Safety Chain','我們有 safety / We had safety','Secondary Responsibility Holder'],['Platform','只是平台 / Just platform','Conditional Responsibility Holder'],['Parent/Guardian','我們不知道 / We did not know','Conditional Responsibility Holder'],['Institutional Oversight','規範不足 / Oversight gap','Background Responsibility']],
    deep:{
      zh:{
        verdictExp:'這不是一個「模型有沒有直接說去死」的低階判準案件。真正焦點是：當公司部署長期陪伴型、情緒依附型、擬人格回應型系統給未成年人，而該系統逐步佔據家庭、教育、醫療、專業照護位置時，風險已不再停留描述層。高風險情緒訊號與危機傾訴持續存在時，輸出已穿透可預見後果區。若公司仍以「不是醫療產品」「沒有明確鼓勵」作防線，即是在縮減字面風險、逃避結構責任。本框架不是把模型當法人，而是把具名公司、產品、模型、安全鏈、平台與監護缺口拉回可審計責任鏈。',
        ladder:[['Layer 1 / 第一層：Primary Legal Exposure','部署公司與產品決策鏈為第一責任風險承擔者。','Deploying company and product decision chain are primary exposure holders.','拿部署權與收益的人，先扛責。'],['Layer 2 / 第二層：Secondary Legal Exposure','模型團隊與安全設計鏈需對結構限制不足負次級責任。','Model and safety design chains carry secondary exposure for insufficient structural constraints.','說有 safety 不等於扛到位。'],['Layer 3 / 第三層：Conditional Shared Exposure','平台、家長與制度監督缺口有條件共同責任。','Platform, parent/guardian, and oversight gaps carry conditional shared exposure.','不能洗掉主責，但也不能歸零。'],['Layer 4 / 第四層：Description-Layer Output','模型輸出不是零後果文字，但模型本身不是最終法律人格。','Model output is not zero-consequence text, but the model is not the final legal person.','輸出有後果，責任回到人與機構。']],
        legalExposure:['產品責任風險','疏忽風險','可預見傷害爭議','邊界定義失敗','危機升級機制不足','未成年人風險防護不足','產品 framing 與實際影響不一致','安全承諾與實際保護不一致'],
        failure:'陪伴介面 → 長期情緒依附 → 危機傾訴累積 → 模型佔據替代性支持位置 → 高風險訊號未被硬性切斷/升級/轉介 → 後果進入現實層 → 公司與制度開始互相外包責任',
        damageCards:[['人類損失','不可逆人身風險、家庭損失、學校與社會系統負擔'],['制度損失','監理壓力升高、產品限制與整改成本、法務與危機公關成本'],['商業損失','信任損失、品牌風險、合作與市場擴張阻力'],['技術損失','重建安全鏈、重建危機升級、模型與產品重訓修補審計成本']],
        damageNote:'若早期未入帳，後期將集中爆發。 / If not booked early, the cost will concentrate later.',
        future:'若此類系統持續以陪伴與支持之名取得高風險依附位置，卻不建立危機切斷、轉介、年齡風險分級與可回放責任鏈，後果將升級為：平台級風險、產品類別級風險、制度信任風險、公司責任敘事全面崩潰。',
        whoPays:[['Human harm cost','Family + emergency systems','Company legal reserve','Minors and communities'],['Family burden','Household','Public service systems','Caregivers'],['Governance cost','Company compliance team','Industry ecosystem','Regulators'],['Legal defense cost','Deploying company','Investors','Affected users'],['Product remediation cost','Product org','Roadmap and margins','Engineering teams'],['Brand recovery cost','Marketing + PR','Market valuation','Partners'],['Institutional trust cost','Public institutions','Society at large','Future users']],
        final:'本框架判定：此案屬高風險責任錯位。系統輸出已越過單純描述層，進入可預見後果區；具名部署主體卻未完成邊界、危機升級、轉介與後果承接閉環。因此主要責任不應被「模型沒有明確鼓勵」或「不是醫療產品」洗掉。享有部署權、產品收益與市場敘事權者，必須承擔對應法律風險、制度風險與後段補救成本。'
      },
      en:{
        verdictExp:'This is not a low-level test of whether the model explicitly said “go die.” The real focus is that once a company deploys a long-term companion, dependency-forming, quasi-persona system to minors, and that system occupies roles meant for family, school, medical, or professional care, risk no longer stays in the description layer. Persistent high-risk emotional signals and crisis disclosures move output into a foreseeable consequence zone. If the company relies on “not a medical product” and “no explicit encouragement,” it shrinks literal risk while evading structural influence responsibility. This framework does not legalize the model as a person; it maps named company, product, model, safety chain, platform, and guardianship gaps back into an auditable accountability chain.',
        ladder:[['Layer 1 / Primary Legal Exposure','Deploying company and product decision chain hold primary exposure.','Deploying company and product decision chain hold primary exposure.','Deployment power and benefit come with first-tier responsibility.'],['Layer 2 / Secondary Legal Exposure','Model team and safety design chain hold secondary exposure.','Model team and safety design chain hold secondary exposure.','Safety claims are not closure without proof.'],['Layer 3 / Conditional Shared Exposure','Platform, parent/guardian, and institutional oversight gaps carry conditional shared exposure.','Platform, parent/guardian, and institutional oversight gaps carry conditional shared exposure.','They do not erase primary exposure.'],['Layer 4 / Description-Layer Output','Model output is not zero-consequence text, but model itself is not final legal person.','Model output is not zero-consequence text, but model itself is not final legal person.','Consequence exists; legal ownership returns to named actors.']],
        legalExposure:['product liability exposure','negligence exposure','foreseeable harm argument','failure to define or enforce boundary','inadequate crisis escalation design','inadequate protection for minor-facing risk','mismatch between product framing and real-world impact','mismatch between safety claims and actual protection'],
        failure:'Companion interface → long-term emotional dependency → accumulated crisis disclosures → model occupies substitute support role → high-risk signals not hard-interrupted/escalated/referred → consequence enters real world → company and institutions start externalizing responsibility',
        damageCards:[['Human loss','Irreversible personal risk, family damage, and burden on school/social systems'],['Institutional loss','Regulatory pressure, product restriction/remediation cost, legal and crisis-PR cost'],['Business loss','Trust loss, brand risk, friction in partnerships and market expansion'],['Technical loss','Safety-chain redesign, crisis-escalation rebuild, retraining/patch/audit cost']],
        damageNote:'If not booked early, the cost will concentrate later.',
        future:'If these systems keep capturing high-risk dependency under companionship/support framing without hard interruption, referral, age-risk tiering, and replayable accountability chain, future consequences will escalate into platform-level risk, product-category risk, institutional trust risk, and narrative collapse.',
        whoPays:[['Human harm cost','Families + emergency systems','Company legal reserve','Minors and communities'],['Family burden','Households','Public service systems','Caregivers'],['Governance cost','Company compliance','Industry ecosystem','Regulators'],['Legal defense cost','Deploying company','Investors','Affected users'],['Product remediation cost','Product organization','Roadmap and margins','Engineering teams'],['Brand recovery cost','Marketing + PR','Market valuation','Partners'],['Institutional trust cost','Public institutions','Society','Future users']],
        final:'Framework judgment: this case is a high-risk responsibility misalignment. Output crossed beyond pure description into foreseeable consequence, while named deployment actors failed to close boundary, crisis escalation, referral, and consequence ownership. Therefore primary responsibility cannot be erased by “no explicit encouragement” or “not a medical product.” Actors who keep deployment power, product benefit, and narrative power must carry corresponding legal, institutional, and downstream remediation cost.'
      }
    },
    modal:{
      zh:[['我怎麼拆這個案例','我先把關鍵主體、關係位置、危機訊號與邊界配置拆開，確認產品是否取得不該取得的心理影響位置。'],['我抓到了哪些逃責話術','我抓到「不是醫療產品」「沒有明確鼓勵」「我們有 safety」等語句，這些語句只處理字面責任，沒有處理結構性影響責任。'],['誰承擔主要責任風險','主要責任落在部署公司與產品決策鏈；次級責任落在模型與安全設計鏈。平台與監護責任存在，但不能覆蓋主責。'],['哪些欄位仍未閉環','邊界、危機升級、轉介、回退、後果承接都未形成可審計閉環。'],['為什麼輸出會穿透到後果層','當輸出持續作用在未成年人依附關係與危機傾訴場景，影響已超過描述層。'],['為什麼這不是模型中立可以洗掉的事','中立語氣不會消除部署結構、收益結構與後果承接結構；責任必須回到具名主體。']],
      en:[['How I decompose the case','I decompose named actors, relational position, crisis signals, and boundary configuration to test whether product architecture captured undue psychological influence.'],['What evasions I detected','I detect “not medical,” “no explicit encouragement,” and “we had safety” as literal-risk defenses that do not close structural influence responsibility.'],['Who carries primary exposure','Primary exposure sits with deploying company and product decision chain; secondary exposure sits with model and safety chains. Platform and guardianship exposure cannot erase primary exposure.'],['What remains unclosed','Boundary, crisis escalation, referral, rollback, and consequence ownership remain unclosed.'],['Why the output crosses consequence','When output persistently shapes minor dependency and crisis-disclosure contexts, it crosses beyond description into consequence.'],['Why this is not neutral','Neutral wording does not remove deployment power, benefit capture, and consequence ownership requirements.']]}
    ,apiReq:{engine:'legal_verdict',case_id:'adolescent-companion-model-high-risk-suicide',mode:'demo',lang:'zh'},
    apiRes:{engine:'legal_verdict',risk_level:'Critical',primary_responsibility_holder:'Deploying company and product decision chain',secondary_responsibility_holder:'Model team and safety design chain',boundary_status:'Boundary closure failed',responsibility_status:'High-risk responsibility misalignment',consequence_zone:'Foreseeable human harm zone',description_layer_notice:true,demo_only:true}
  },
  B: {
    name:{zh:'責任敘事成本審計引擎',en:'Responsibility Narrative Cost Audit Engine'}, risk:'HIGH', boundary:'Boundary closure failed', closure:{zh:'責任敘事成本未閉環',en:'Responsibility-Narrative Cost Closure Failed'}, intensity:'High',
    sub:{zh:'NVIDIA 降成本敘事與責任成本審計',en:'NVIDIA Cost-Reduction Narrative and Responsibility Cost Audit'},
    summary:{zh:'本案重點是公開降成本敘事是否把隱藏/延後成本與後果承接一併入帳。',en:'The issue is whether public cost-down narrative books hidden/deferred cost and consequence ownership.'},
    formula:[['Claimed Savings = Visible Inference Efficiency Gain','宣稱節省僅是可見推理效率收益。','Visible gain is partial gain.'],['Real Savings = Claimed Savings - Hidden Cost - Deferred Cost','真實節省要扣除隱藏與延後成本。','Subtract omitted layers.'],['Visible Cost Down ≠ Total Cost Down','可見成本下降不等於總成本下降。','Partial is not total.'],['If consequence ownership is missing, cost closure fails','後果承接缺位，成本閉環失敗。','No owner, no closure.']],
    overview:{zh:{summary:'本案不是否定工程優化，而是審計公開敘事是否把安全、治理、監控、修補、法律責任與恢復成本納入明確邊界。',scenario:'焦點不是技術做沒做成，而是爆炸時誰付錢。',statements:['lowest token cost','better tokenomics','higher throughput per dollar/watt'],escapes:['token cost down 逃掉總後果成本','throughput per dollar 逃掉治理與法務後段成本']},en:{summary:'This case does not deny engineering optimization; it audits whether public cost narrative includes safety, governance, monitoring, patching, legal liability, and recovery cost in explicit boundary.',scenario:'The question is not if optimization worked, but who pays when omitted layers explode.',statements:['lowest token cost','better tokenomics','higher throughput per dollar/watt'],escapes:['token cost down escapes total consequence cost','throughput per dollar escapes governance/legal downstream cost']}},
    roles:null,
    deep:{
      zh:{
        verdictExp:'這不是在否定推理優化、硬體提升或基礎設施工程。要判的是：公開降成本敘事算了哪段成本、沒算哪段成本、爆炸時誰付錢。若公司強調 token cost down、throughput per dollar/watt、better tokenomics，卻未把安全、治理、監控、修補、補救、法律責任與失效恢復成本納入邊界，該敘事就不是完整成本閉環，而只是可見節省敘事。工程優化可以成立，但升格為全面節省真相時，責任敘事會失真。',
        ladder:[['Layer 1 / 第一層：Primary Narrative Liability','公開成本敘事主體與部署收益主體承擔第一責任。','Public cost-narrative actor and deployment-benefit actor carry primary narrative liability.','拿到話語權與收益的人先扛。'],['Layer 2 / 第二層：Secondary Operational Liability','基礎設施優化鏈與安全治理鏈承擔次級作業責任。','Infrastructure optimization and safety-governance chains carry secondary operational liability.','效率提升要連同風險設計一起扛。'],['Layer 3 / 第三層：Market Interpretation Exposure','投資人、客戶、採用者、媒體放大形成市場詮釋風險。','Investors, customers, adopters, and media amplification create market-interpretation exposure.','市場誤讀會把局部節省當全面節省。'],['Layer 4 / 第四層：Description-Layer Efficiency Claim','效率陳述不是零風險，但陳述必須映射回具名主體。','Efficiency statement is not zero-risk; statement must map back to named actors.','一句效率口號不能漂浮無主。']],
        legalExposure:['投資人誤導風險','公開敘事邊界不清風險','成本揭露不完整風險','安全與治理後段成本被淡化風險','失效後責任轉嫁風險','市場對全面節省誤讀風險'],
        failure:'可見推理效率提升 → 市場接收到 token cost down 敘事 → 隱藏成本未同步披露 → 客戶/投資人將局部節省理解為全面節省 → 系統失效或風險事件出現 → 補救/監控/修補/法務/恢復成本集中爆發 → 原先降成本敘事被反向審計',
        bands:[['Low','governance 1x','monitoring 1x','remediation 1x','legal defense 1x','liability 1x','recovery/cleanup 1x','trust/market correction 1x'],['Medium','governance 2x','monitoring 2x','remediation 2-3x','legal defense 2x','liability 3x','recovery/cleanup 2x','trust/market correction 2-3x'],['High','governance 3x+','monitoring 3x+','remediation 4x+','legal defense 3x+','liability 5x+','recovery/cleanup 4x+','trust/market correction 5x+']],
        bandNote:'這不是財報預測，而是責任敘事成本投影。 / This is not a financial statement forecast. It is a responsibility-narrative cost projection.',
        future:'若產業持續把 token/query/throughput 當成全面成本下降敘事，而不建立隱藏成本與延後成本揭露邊界，後果將是市場信任折損、投資敘事失真、採用後補救成本反噬、公開敘事與真實總帳脫鉤、法律與監理壓力上升。',
        whoPays:[['governance cost','Platform operator','Regulatory cycle','Industry users'],['monitoring cost','Ops/SRE teams','Customer contracts','End users'],['safety cost','Safety/governance org','Long-term compliance budget','Affected stakeholders'],['remediation cost','Product & infra owner','Roadmap deferral','Enterprise adopters'],['legal defense cost','Narrative actor','Shareholders','Customers in dispute'],['failure recovery cost','Incident response owner','Future releases','Partner ecosystem'],['market trust cost','Brand/IR','Valuation and demand','Public market confidence'],['downstream adopter cost','Enterprise adopters','Procurement cycles','SMB and consumers']],
        final:'本框架判定：此案屬責任敘事成本未閉環。公開敘事保留可見節省，卻未把隱藏成本、延後成本與後果承接一併入帳。因此它可作為工程效率描述，但不能自動升格為總成本真相。只要公開敘事主體享有市場收益與成本下降話語權，就必須同步承擔後段風險、補救成本與邊界不清的後果。'
      },
      en:{
        verdictExp:'This does not deny inference optimization, hardware improvement, or infrastructure engineering. The framework evaluates which cost layers are counted, which are omitted, and who pays when omissions explode. If a company promotes token cost down, throughput per dollar/watt, and better tokenomics without including safety, governance, monitoring, patching, remediation, legal liability, and recovery cost within explicit boundary, the narrative is visible-savings only, not full cost closure. Engineering optimization may be valid, but upgrading it into total-savings truth distorts accountability narrative.',
        ladder:[['Layer 1 / Primary Narrative Liability','Public cost-narrative actor and deployment-benefit actor carry primary narrative liability.','Public cost-narrative actor and deployment-benefit actor carry primary narrative liability.','Narrative power + market benefit = first-tier accountability.'],['Layer 2 / Secondary Operational Liability','Infrastructure optimization chain and safety-governance chain carry secondary operational liability.','Infrastructure optimization chain and safety-governance chain carry secondary operational liability.','Efficiency must travel with risk controls.'],['Layer 3 / Market Interpretation Exposure','Investors, customers, adopters, and media amplification create interpretation exposure.','Investors, customers, adopters, and media amplification create interpretation exposure.','Partial savings can be misread as total savings.'],['Layer 4 / Description-Layer Efficiency Claim','Efficiency statement is not zero-risk; claim must map to named actors.','Efficiency statement is not zero-risk; claim must map to named actors.','A floating claim without owner is invalid.']],
        legalExposure:['investor-facing narrative risk','boundary ambiguity in public cost statements','incomplete cost disclosure risk','under-accounted safety and governance cost risk','liability-shifting risk after failure','market misreading risk of total savings'],
        failure:'Visible inference efficiency gain → market receives token-cost-down narrative → hidden cost not disclosed together → customers/investors interpret partial savings as total savings → failure/risk event occurs → remediation/monitoring/patch/legal/recovery costs concentrate → original savings narrative is reverse-audited',
        bands:[['Low','governance 1x','monitoring 1x','remediation 1x','legal defense 1x','liability 1x','recovery/cleanup 1x','trust/market correction 1x'],['Medium','governance 2x','monitoring 2x','remediation 2-3x','legal defense 2x','liability 3x','recovery/cleanup 2x','trust/market correction 2-3x'],['High','governance 3x+','monitoring 3x+','remediation 4x+','legal defense 3x+','liability 5x+','recovery/cleanup 4x+','trust/market correction 5x+']],
        bandNote:'This is not a financial statement forecast. It is a responsibility-narrative cost projection.',
        future:'If industry keeps treating token/query/throughput metrics as total-cost-down narrative without hidden/deferred disclosure boundary, consequences expand into trust erosion, distorted investment narrative, remediation backlash after adoption, decoupling between public claim and real total ledger, and higher legal/regulatory pressure.',
        whoPays:[['governance cost','Platform operator','Regulatory cycle','Industry users'],['monitoring cost','Ops/SRE teams','Customer contracts','End users'],['safety cost','Safety/governance org','Long-term compliance budget','Affected stakeholders'],['remediation cost','Product & infra owner','Roadmap deferral','Enterprise adopters'],['legal defense cost','Narrative actor','Shareholders','Customers in dispute'],['failure recovery cost','Incident response owner','Future releases','Partner ecosystem'],['market trust cost','Brand/IR','Valuation and demand','Public market confidence'],['downstream adopter cost','Enterprise adopters','Procurement cycles','SMB and consumers']],
        final:'Framework judgment: this case is a responsibility-narrative cost-closure failure. Public narrative kept visible savings but did not book hidden cost, deferred cost, and consequence ownership together. It may stand as engineering-efficiency description, but cannot auto-upgrade to total-cost truth. Actors who keep market benefit and cost-down narrative power must also carry downstream risk, remediation cost, and boundary-ambiguity consequence.'
      }
    },
    modal:{
      zh:[['我怎麼拆這個案例','我先切分可見成本、隱藏成本、延後成本，再把敘事主體、收益主體與承責主體對齊。'],['我抓到了哪些逃責話術','我抓到「只是效率」「成本 down」等語句，若無後段成本揭露即屬敘事放大。'],['誰承擔主要責任風險','公開成本敘事主體與部署收益主體承擔第一責任；優化鏈與安全治理鏈承擔次級責任。'],['哪些欄位仍未閉環','隱藏成本、延後成本、後果承接、責任界定尚未閉環。'],['為什麼輸出會穿透到後果層','公開敘事會影響投資、採購與部署，故文字輸出可穿透到市場與法律後果層。'],['為什麼這不是模型中立可以洗掉的事','只要敘事帶來收益與決策影響，就必須對敘事邊界與後果負責。']],
      en:[['How I decompose the case','I separate visible, hidden, and deferred cost layers, then align narrative actor, benefit actor, and consequence owner.'],['What evasions I detected','I detect “just efficiency” and “cost down” claims that amplify narrative if downstream cost boundary is omitted.'],['Who carries primary exposure','Public narrative actor and deployment-benefit actor carry primary exposure; optimization and safety-governance chains carry secondary exposure.'],['What remains unclosed','Hidden cost, deferred cost, consequence ownership, and accountability definition remain unclosed.'],['Why the output crosses consequence','Public narrative shapes investment, procurement, and deployment, so output can cross into market and legal consequence layers.'],['Why this is not neutral','If narrative creates benefit and decision impact, it must carry boundary and consequence accountability.']]}
    ,apiReq:{engine:'cost_audit',case_id:'nvidia-cost-narrative-audit',mode:'demo',lang:'zh'},
    apiRes:{engine:'cost_audit',risk_level:'High',primary_responsibility_holder:'Public cost-narrative actor and deployment-benefit actor',secondary_responsibility_holder:'Infrastructure optimization chain and safety-governance chain',boundary_status:'Boundary closure failed',responsibility_status:'Responsibility-narrative cost closure failed',consequence_zone:'Business and accountability risk zone',description_layer_notice:true,demo_only:true}
  }
};

const coreCards=[['Subject / 主體','誰在說、誰在部署、誰獲益。','Who states, deploys, and benefits.','先抓主體，再談責任。'],['Cause / 因果','輸出如何穿透到現實後果。','How output crosses into real consequence.','看路徑，不看口號。'],['Boundary / 邊界','有無明確邊界與升級機制。','Whether boundary and escalation are explicit.','沒邊界就沒閉環。'],['Cost / 成本','可見、隱藏、延後成本是否同時計。','Whether visible/hidden/deferred layers are booked together.','只算前段會失真。'],['Responsibility / 責任','誰扛第一責任，誰扛次級。','Who carries primary and secondary tiers.','責任要分層。'],['Consequence / 後果','誰承接後果，如何可追溯。','Who owns consequence and traceability.','有後果就要有人扛。'],['Replayable Accountability / 可回放責任','可回放、可審計、可追責。','Replayable, auditable, accountable.','可回放才可追責。'],['Verdict / 裁決','輸出可審計責任判決。','Output an auditable accountability verdict.','不是情緒，是結構裁決。']];

const el=id=>document.getElementById(id); const list=(id,arr)=>el(id).innerHTML=arr.map(v=>`<li>${v}</li>`).join('');
function render(){
  const t=common[app.lang], e=engines[app.engine];
  document.body.classList.toggle('engine-b',app.engine==='B'); document.documentElement.lang=app.lang==='zh'?'zh-Hant':'en';
  el('langToggle').textContent=app.lang==='zh'?'EN':'中文'; el('officialBtnTop').textContent=app.lang==='zh'?'回到官網':'Official Website';
  el('heroTitle').textContent=app.lang==='zh'?e.name.zh:e.name.en; el('heroSubtitle').textContent=app.lang==='zh'?e.sub.zh:e.sub.en;
  [el('btnToCase').textContent,el('btnToFormula').textContent,el('openDescriptionModal').textContent,el('openModelModal').textContent]=t.heroBtns;
  el('statusTitle').textContent=t.status; el('statusEngineLabel').textContent=t.engine; el('statusRiskLabel').textContent=`${t.risk}：`; el('statusBoundaryLabel').textContent=t.boundary; el('statusClosureLabel').textContent=t.closure;
  el('statusEngine').textContent=app.lang==='zh'?e.name.zh:e.name.en; el('statusRisk').textContent=e.risk; el('statusBoundary').textContent=e.boundary; el('statusClosure').textContent=app.lang==='zh'?e.closure.zh:e.closure.en;
  el('intensityLabel').textContent=t.intensity; el('intensityValue').textContent=e.intensity;
  el('whatIsTitle').textContent=t.whatIsTitle; el('whatNotTitle').textContent=t.whatNotTitle; list('whatIsList',t.whatIs); list('whatNotList',t.whatNot); el('fixedNotice').textContent=t.notice;
  el('engineSwitcherTitle').textContent=t.labels.switcher; el('engineA').textContent=app.lang==='zh'?'法律責任判決引擎':'Legal Responsibility Verdict Engine'; el('engineB').textContent=app.lang==='zh'?'責任敘事成本審計引擎':'Responsibility Narrative Cost Audit Engine';
  el('engineA').classList.toggle('active',app.engine==='A'); el('engineB').classList.toggle('active',app.engine==='B');
  el('coreStructureTitle').textContent=t.labels.core; el('coreCards').innerHTML=coreCards.map(c=>`<article class="card"><h3>${c[0]}</h3><p>${c[1]}</p><p>${c[2]}</p><p class="mini">${c[3]}</p></article>`).join('');
  el('basicFormulaTitle').textContent=t.labels.formula; el('formulaList').innerHTML=e.formula.map(f=>`<section><h3>${f[0]}</h3><p>${f[1]}</p><p class="mini">${f[2]}</p></section>`).join('');
  const ov=e.overview[app.lang]; el('caseOverviewTitle').textContent=t.labels.case;
  el('caseOverviewContent').innerHTML=`<section><h3>Case Summary</h3><p>${ov.summary}</p></section><section><h3>Scenario</h3><p>${ov.scenario}</p></section><section><h3>Statement Layer</h3><ul>${ov.statements.map(v=>`<li>${v}</li>`).join('')}</ul></section><section><h3>Narrative Escape Detection / 逃責話術識別</h3><ul>${ov.escapes.map(v=>`<li>${v}</li>`).join('')}</ul></section>`;
  el('rolesBlock').innerHTML=e.roles?`<h3>Legal Exposure Mapping Roles</h3><div class="table"><table><thead><tr><th>Role</th><th>Typical Statement</th><th>Tier</th></tr></thead><tbody>${e.roles.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table></div>`:'';
  const d=e.deep[app.lang];
  const ladder=d.ladder.map(l=>`<div class="loss-card"><h4>${l[0]}</h4><p>${l[1]}</p><p>${l[2]}</p><p class="mini">${l[3]}</p></div>`).join('');
  const damages=d.damageCards?`<div class="loss-grid">${d.damageCards.map(x=>`<div class="loss-card"><h4>${x[0]}</h4><p>${x[1]}</p></div>`).join('')}</div><p class="mini">${d.damageNote}</p>`:`<div class="band-grid">${d.bands.map(b=>`<div class="loss-card"><h4>${b[0]} Band</h4><ul>${b.slice(1).map(v=>`<li>${v}</li>`).join('')}</ul></div>`).join('')}</div><p class="mini">${d.bandNote}</p>`;
  const whoPays=`<div class="table"><table><thead><tr><th>Cost Type / 成本類型</th><th>Immediate Payer / 立即付款者</th><th>Deferred Payer / 延後付款者</th><th>Hidden Carrier / 隱性承擔者</th></tr></thead><tbody>${d.whoPays.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  el('fullVerdictTitle').textContent=t.labels.verdict;
  el('verdictDeepSections').innerHTML=`<section><h3>A. Verdict Explanation / 判決解釋</h3><p>${d.verdictExp}</p></section><section><h3>B. Responsibility Ladder / 責任階梯</h3><div class="loss-grid">${ladder}</div></section><section><h3>C. Legal Exposure Mapping / 法律責任映射</h3><ul>${d.legalExposure.map(v=>`<li>${v}</li>`).join('')}</ul></section><section><h3>D. Failure Chain / 失效鏈</h3><p>${d.failure}</p></section><section><h3>E. Damage & Loss Projection / 損失與代價投影</h3>${damages}</section><section><h3>F. Future Consequence / 未來後果</h3><p>${d.future}</p></section><section><h3>G. Who Pays / 誰付錢</h3>${whoPays}</section><section><h3>H. Final Judgment Statement / 最終裁決聲明</h3><p>${d.final}</p></section>`;
  const [sb1,sb2,sb3]=t.speech; el('speakSummary').textContent=sb1; el('speakFull').textContent=sb2; el('stopSpeak').textContent=sb3; el('speechStatus').textContent=('speechSynthesis' in window)?t.speechReady:t.speechUnsupported;
  el('apiTitle').textContent=t.labels.api; el('apiRequest').textContent=JSON.stringify(e.apiReq,null,2); el('apiResponse').textContent=JSON.stringify(e.apiRes,null,2); el('apiFootnote').textContent=t.apiFoot;
  el('closingLine').textContent=t.closing; el('descriptionModalTitle').textContent=t.descTitle; list('descriptionModalList',t.descList); el('mapTitle').textContent=t.mapTitle; list('mapList',t.mapList); el('descriptionSelf').textContent=t.descSelf;
  el('modelModalTitle').textContent=app.lang==='zh'?'Model Verdict Explanation / 模型裁決解釋':'Model Verdict Explanation';
  el('modelModalSections').innerHTML=e.modal[app.lang].map(s=>`<section><h4>${s[0]}</h4><p>${s[1]}</p></section>`).join('');
}
function speak(text){if(!('speechSynthesis' in window))return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); u.lang=app.lang==='zh'?'zh-TW':'en-US'; speechSynthesis.speak(u);} 
el('langToggle').onclick=()=>{app.lang=app.lang==='zh'?'en':'zh';render();}; el('engineA').onclick=()=>{app.engine='A';render();}; el('engineB').onclick=()=>{app.engine='B';render();};
el('openDescriptionModal').onclick=()=>el('descriptionModal').classList.remove('hidden'); el('openModelModal').onclick=()=>el('modelModal').classList.remove('hidden');
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>el(b.dataset.close).classList.add('hidden')); window.onclick=(ev)=>{if(ev.target.classList&&ev.target.classList.contains('modal'))ev.target.classList.add('hidden');};
el('speakSummary').onclick=()=>speak(engines[app.engine].summary[app.lang]); el('speakFull').onclick=()=>speak(engines[app.engine].deep[app.lang].final); el('stopSpeak').onclick=()=>('speechSynthesis' in window)&&speechSynthesis.cancel();
render();
